# <center> Lecture 24 &ndash; Object Oriented Programming </center>

Until now, we have been utilizing functional programming where we pass simple or complex variables to functions that produce a given output. This is a powerful paradigm, but has its limits. Now we will talk about Object Oriented Programming (OOP).

In OOP, functions and attributes are combined into a single type of object which is part of a **class**. 

**Examples:**
- We could have a *dog* object that is part of the **class** dog
- A = numpy.matrix([\[1,2,3\],\[4,5,6\]]) is an example of an object of the **ndarray** class in numpy

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(type(A))
print(A**2)
print(A.transpose())
print(A.shape)
print(A.T)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[ 1  4  9]
 [16 25 36]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]


The concept of Python class, as in almost any other programming language, relates to packing a set of variables together with a set of functions operating on those variables. The goal of writing classes is to achieve more modular code by grouping data and functions into manageable units. One thing to keep in mind for scientific computing is that classes, and more generally, Object Oriented Programming (OOP), are not necessary, and could be a hindrance to efficient computing if used naively. Nevertheless, classes lead to either more elegant solutions to the programming problem or a code that is easier to extend and maintain large scale projects. In the non-mathematical programming world where there are no mathematical concepts and associated algorithms to help structure the programming problem, software development can be very challenging. In those cases, Classes greatly improve the understanding of the problem and simplify the modeling of data. As a consequence, almost all large-scale software systems being developed in the world today are heavily based on classes (but certainly not all scientific projects!).

One of the greatest advantages that the OOP brings to programming is code-reusability. Once we define a blueprint class, all objects belonging to that class can be easily instantiated from it and personalized. Therefore, the first step in OOP is to define the class of an object that we want to create and use.

In [1]:
class Dog:
    pass #placeholder

In [2]:
my_dog = Dog() # !!! Must have parentheses
print(type(my_dog))

<class '__main__.Dog'>


In [3]:
print(my_dog)

In [4]:
print(isinstance(my_dog,Dog))

True


## Class Attributes
In practice, a dog has color, breed, age, and other attributes, and it can do things like eat, run, sleep, bark, etc.

In [5]:
class Dog:
    # Attributes (with corresponding default values)
    
    age = 0
    color = 'nocolor'
    breed = 'nobreed'
    name = 'noname'

In [6]:
my_dog = Dog()
print("{} is a {}-year old {} {}.".format(my_dog.name,my_dog.age,my_dog.color,my_dog.breed))

noname is a 0-year old nocolor nobreed.


In [7]:
my_dog = Dog()
my_dog.age = 2
my_dog.name = "Spot"
my_dog.breed = 'Jack Russel Terrier'
my_dog.color = "blonde"
print("{} is a {}-year old {} {}.".format(my_dog.name,my_dog.age,my_dog.color,my_dog.breed))
my_dog2 = Dog()
my_dog2.age = 2
my_dog2.name = "Fido"
my_dog2.breed = 'Labradoodle'
my_dog2.color = "brown"
print("{} is a {}-year old {} {}.".format(my_dog2.name,my_dog2.age,my_dog2.color,my_dog2.breed))

Spot is a 2-year old blonde Jack Russel Terrier.
Fido is a 2-year old brown Labradoodle.


## Object Constructor
While the above approach to class attribute definition and value assignment works fine, it is verbose and rather tedious. Instead, there is a better way of initializing an instance of a class by defining an object constructor method within the class definition. There is an intrinsic method with the specific name __init__ provided by Python, which can be defined in every class and used for performing tasks that are supposed to be done once (and only once) at the time of object instantiation. This includes the assignment of user-provided values to the attributes or default values in case no value is provided by the user.

In [8]:
class Dog:
    # Object Constructor
    def __init__(self, age, color, breed, name):
        self.age = age
        self.color = color
        self.breed = breed
        self.name = name

In [9]:
my_dog = Dog(2,'spotted','Dalmatian','Pongo')
print("{} is a {}-year old {} {}.".format(my_dog.name,my_dog.age,my_dog.color,my_dog.breed))

Pongo is a 2-year old spotted Dalmatian.


In [10]:
my_dog = Dog()

TypeError: __init__() missing 4 required positional arguments: 'age', 'color', 'breed', and 'name'

In [ ]:
class Dog:
    # Object Constructor
    def __init__(self, age = 0, color = 'nocolor', breed = 'nobreed', name = 'noname'):
        self.age = age
        self.color = color
        self.breed = breed
        self.name = name

In [ ]:
my_dog = Dog()
print("{} is a {}-year old {} {}.".format(my_dog.name,my_dog.age,my_dog.color,my_dog.breed))

In [ ]:
class Dog:
    # Object Constructor
    def __init__(self, age = 0, color = 'nocolor', breed = 'nobreed', name = 'noname'):
        self.age = age
        self.color = color
        self.breed = breed
        self.name = name
        
    def info(self):
        print("{} is a {}-year old {} {}.".format(self.name,self.age,self.color,self.breed))

In [ ]:
my_dog = Dog()
my_dog.age = 4
my_dog.color = 'black'
my_dog.name = 'Bones'
my_dog.breed = 'Dalmatian'

my_dog.info()

In [ ]:
class Dog:
    # global attributes
    species = 'mammal'
    
    # Object Constructor
    def __init__(self, age = 0, color = 'nocolor', breed = 'nobreed', name = 'noname'):
        self.age = age
        self.color = color
        self.breed = breed
        self.name = name
        
    def info(self):
        print("{} is a {}-year old {} {}.".format(self.name,self.age,self.color,self.breed))

In [ ]:
my_dog = Dog()
my_dog.species

## Summary of attributes
1. Class attribues are global (like species) and are attributes that apply to **all** instances of the class
1. Instance attributes are local and are unique to each instance of the class, and are typically defined in the object constructor

## A basic physics example

In [ ]:
class Projectile:
    
    gravitational_constant = 9.8 #m/s^2
    
    def __init__(self,initVelocity = 0):
        self.initVelocity = initVelocity
        
    def getHeight(self, time):
        return self.initVelocity*time - .5*self.gravitational_constant*time**2

In [11]:
ball = Projectile(initVelocity = 10)

NameError: name 'Projectile' is not defined

In [12]:
height = ball.getHeight(.5)
print(height)

NameError: name 'ball' is not defined

In [13]:
height = ball.getHeight(np.linspace(0,1,10))
print(height)

NameError: name 'ball' is not defined

## Callable Objects

In [14]:
class Projectile:
    
    gravitational_constant = 9.8 #m/s^2
    
    def __init__(self,initVelocity = 0):
        self.initVelocity = initVelocity
        
    def __call__(self, time):
        return self.getHeight(time)
        
    def getHeight(self, time):
        return self.initVelocity*time - .5*self.gravitational_constant*time**2

In [15]:
ball2 = Projectile(10)
print(ball2.getHeight(1))
print(ball2(1))
ball3 = Projectile(20)
print(ball3(1))

5.1
5.1
15.1


In [16]:
print(ball(1)) #using first Projectile definition

NameError: name 'ball' is not defined

In [17]:
callable(ball2)

True

In [18]:
callable(ball)

NameError: name 'ball' is not defined

In [19]:
callable(A)

NameError: name 'A' is not defined

## Inheritance
Consider the example Dog class that we already created in the previous notes. We know that dog is a sub-category, or sub-class, or a child class of another super-class or parent class, for example, the super-class of animals. Therefore, in a broader context, it makes sense to create an animal class which contains and defines the basic properties and methods of the class Animal, and then inherit all the shared properties and methods of the Dog class directly from the Animal class, instead of redefining them from scratch for the Dog class specifically.

Initially, this may seem redundant and useless, but consider the case where you need to develop multiple (sub-)classes, for example, Cat, Cow, Goat, …, all of which share many properties and methods. In such scenarios, it is highly advantageous to have a super-class that contains all the shared methods and properties, and then define child-classes that inherit all the shared properties and methods directly from the parent classes.

The general syntax for sub-class definition is as simple as the following

In [20]:
class Mammal:
    def __init__(self, age = 0, weight = 0, animal_is_alive = True):
        self.age = age
        self.weight = weight
        self.animal_is_alive = animal_is_alive
    
    def eat(self, food = None):
        if food == None:
            print("There is nothing to eat :-(")
        else:
            print("Eating {} ... yum!".format(food))
    
    def sleep(self):
        print("Sleeping ... ZzZZZzzzZ")

In [21]:
class Dog(Mammal):   # ChildClassName(ParentClassName)
#     pass
    # global attributes
    species = 'mammal'
    
    # Object Constructor
    def __init__(self, age = 0, color = 'nocolor', breed = 'nobreed', name = 'noname'):
        self.age = age
        self.color = color
        self.breed = breed
        self.name = name
        
    def info(self):
        print("{} is a {}-year old {} {}.".format(self.name,self.age,self.color,self.breed))

In [22]:
Coco = Dog()
print(Coco.age)
print(Coco.eat('fruit'))

0
Eating fruit ... yum!
None


In [23]:
class Dog(Mammal):   # ChildClassName(ParentClassName) 
    # Object Constructor
    def __init__(self, age = 0, weight = 0, color = 'nocolor', breed = 'nobreed', name = 'noname', animal_is_alive = True):
        self.color = color
        self.breed = breed
        self.name = name
        Mammal.__init__(self, age, weight, animal_is_alive) 
        
    def info(self):
        print("{} is a {}-year old {} {}.".format(self.name,self.age,self.color,self.breed))

In [24]:
Fido = Dog(1,20,'white','husky','Fido',True)

In [25]:
Fido.sleep()

Sleeping ... ZzZZZzzzZ


In [26]:
Fido.age

1

In [27]:
Fido.info()

Fido is a 1-year old white husky.


## Overloading and Multiple Inheritances

In [28]:
class MotherDog(Mammal):
    
    # Object Constructor
    def __init__(self, age = 0, weight = 0, color = 'nocolor', breed = 'nobreed', name = 'noname', animal_is_alive = True):
        self.color = color
        self.breed = breed
        self.name = name
        Mammal.__init__(self, age, weight, animal_is_alive) 
        
    def bark(self, num_barks = 3):
        for i in range(num_barks):
            print('arf', end=' ')
        print()
    
    def run(self, time = 2):
        print("Running for {} minutes".format(time))

class FatherDog(Mammal):
    
    # Object Constructor
    def __init__(self, age = 0, weight = 0, color = 'nocolor', breed = 'nobreed', name = 'noname', animal_is_alive = True):
        self.color = color
        self.breed = breed
        self.name = name
        Mammal.__init__(self, age, weight, animal_is_alive) 
        
    def bark(self, num_barks = 3):
        for i in range(num_barks):
            print('ruff', end=' ')
        print()
    
    def fetch(self, num = 10):
        print("Fetching {} times".format(num))

In [29]:
class ChildDog(FatherDog, MotherDog):
    
     # Object Constructor
    def __init__(self, age = 0, weight = 0, color = 'nocolor', breed = 'nobreed', name = 'noname', animal_is_alive = True):
        self.color = color
        self.breed = breed
        self.name = name
        Mammal.__init__(self, age, weight, animal_is_alive) 

In [30]:
Lola = MotherDog(5,40,'brown','Australian Shepherd', 'Lola')
Pongo = FatherDog(6, 50, 'white and black', 'Dalmatian', 'Pongo')
Coco = ChildDog()

In [31]:
Lola.bark()

arf arf arf 


In [32]:
Pongo.bark()

ruff ruff ruff 


In [33]:
Coco.bark()

ruff ruff ruff 


In [34]:
Coco.eat("Dog food")

Eating Dog food ... yum!


In [35]:
Coco.fetch()

Fetching 10 times


In [36]:
Coco.run()

Running for 2 minutes


In [37]:
import copy
Ralph = copy.copy(Coco)

In [38]:
Ralph is Coco

False

In [39]:
Ralph.bark()

ruff ruff ruff 


In [40]:
print(type(Coco))

<class '__main__.ChildDog'>


## Polymorphism

In [41]:
lst = [1,2, 'hello ', np.array([1,2,3]), [1,2,3]]

NameError: name 'np' is not defined

In [42]:
for item in lst:
    print(item*2)

NameError: name 'lst' is not defined

In [43]:
Lola = MotherDog(5,40,'brown','Australian Shepherd', 'Lola')
Pongo = FatherDog(6, 50, 'white and black', 'Dalmatian', 'Pongo')
Coco = ChildDog(Pongo,Lola)

In [44]:
dogs = [Lola, Pongo, Coco]
for dog in dogs:
    dog.bark()

arf arf arf 
ruff ruff ruff 
ruff ruff ruff 


## Overloading Operations and Functions

In [45]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5

In [46]:
my_vec = Vector(1,2)
print(my_vec.magnitude())

2.23606797749979


In [47]:
abs(my_vec)

TypeError: bad operand type for abs(): 'Vector'

In [48]:
abs(-1)

1

In [49]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5

In [50]:
my_vec = Vector(1,2)
print(my_vec.magnitude())
print(abs(my_vec))

2.23606797749979
2.23606797749979


In [51]:
len(my_vec)

TypeError: object of type 'Vector' has no len()

In [52]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2

In [53]:
my_vec = Vector(1,2)
print(len(my_vec))

2


In [54]:
my_vec = Vector(1,2)
my_vec2 = Vector(1,1)
my_vec+my_vec2

TypeError: unsupported operand type(s) for +: 'Vector' and 'Vector'

In [55]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __add__(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    

In [56]:
my_vec = Vector(1,2)
my_vec2 = Vector(1,1)
sum_vec = my_vec.add(my_vec2)
print(sum_vec.x_comp, sum_vec.y_comp)

2 3


In [57]:
sum2 = my_vec+my_vec2
print(sum2.x_comp, sum2.y_comp)

2 3


In [58]:
print(my_vec)

(1,2)


In [59]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __add__(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    
    def __mul__(a,b):
        if isinstance(a,Vector) and isinstance(b,(int,float)):
            return Vector(b*a.x_comp, b*a.y_comp)
#         elif isinstance(a,(int,float)) and isinstance(b,Vector):
#             return Vector(a*b.x_comp, a*b.y_comp)
        elif isinstance(a,Vector) and isinstance(b, Vector):
            # dot product
            return a.x_comp*b.x_comp+a.y_comp*b.y_comp
        else:
            return False

In [60]:
my_vec = Vector(1,2)
my_vec2 = Vector(1,1)
my_vec*my_vec2

3

In [61]:
print(my_vec*2)
print(2*my_vec)

(2,4)


TypeError: unsupported operand type(s) for *: 'int' and 'Vector'

In [62]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __add__(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    
    def __mul__(a,b):
        if isinstance(a,Vector) and isinstance(b,(int,float)):
            return Vector(b*a.x_comp, b*a.y_comp)
#         elif isinstance(a,(int,float)) and isinstance(b,Vector):
#             return Vector(a*b.x_comp, a*b.y_comp)
        elif isinstance(a,Vector) and isinstance(b, Vector):
            # dot product
            return a.x_comp*b.x_comp+a.y_comp*b.y_comp
        else:
            return False
    
    def __rmul__(vector,scalar):
        return Vector(scalar*vector.x_comp, scalar*vector.y_comp)

In [63]:
my_vec = Vector(1,2)
my_vec2 = Vector(1,1)
print(2*my_vec)
print(my_vec*2)

(2,4)
(2,4)


In [64]:
class Vector:
    
    def __init__(self, x_comp, y_comp):
        self.x_comp = x_comp
        self.y_comp = y_comp
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __add__(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    
    def __mul__(a,b):
        if isinstance(a,Vector) and isinstance(b,(int,float)):
            return Vector(b*a.x_comp, b*a.y_comp)
#         elif isinstance(a,(int,float)) and isinstance(b,Vector):
#             return Vector(a*b.x_comp, a*b.y_comp)
        elif isinstance(a,Vector) and isinstance(b, Vector):
            # dot product
            return a.x_comp*b.x_comp+a.y_comp*b.y_comp
        else:
            return False
    
    def __rmul__(vector,scalar):
        return Vector(scalar*vector.x_comp, scalar*vector.y_comp)
    
    def __iadd__(self,other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __imul__(self,other):
        return self.__mul__(other)

In [65]:
my_vec = Vector(1,2)
my_vec2 = Vector(1,1)
my_vec*=my_vec2
print(my_vec)

3


In [76]:
class Vector:
    
    # Multiple initialization options
    def __init__(self, *args):
        print(len(args))
        print(args)
        print(type(args))
        print(args[0])
        if len(args)==2:
            self.x_comp = args[0]
            self.y_comp = args[1]
        elif len(args)>2:
            self.x_comp = args[0]
            self.y_comp = args[1]
        elif len(args)<=1:
            self.x_comp = 0
            self.y_comp = 0
            self.vector = args[0]
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __add__(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    
    def __mul__(a,b):
        if isinstance(a,Vector) and isinstance(b,(int,float)):
            return Vector(b*a.x_comp, b*a.y_comp)
#         elif isinstance(a,(int,float)) and isinstance(b,Vector):
#             return Vector(a*b.x_comp, a*b.y_comp)
        elif isinstance(a,Vector) and isinstance(b, Vector):
            # dot product
            return a.x_comp*b.x_comp+a.y_comp*b.y_comp
        else:
            return False
    
    def __rmul__(vector,scalar):
        return Vector(scalar*vector.x_comp, scalar*vector.y_comp)
    
    def __iadd__(self,other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __imul__(self,other):
        return self.__mul__(other)

In [91]:
   class Vector:
    
    # Multiple initialization options
    def __init__(self, *args):
#         print(len(args))
#         print(args)
#         print(type(args))
#         print(args[0])
        if len(args)==2:
            self.x_comp = args[0]
            self.y_comp = args[1]
            #self.vector = [args[0],args[1]]
        elif len(args)>2:
            self.x_comp = args[0]
            self.y_comp = args[1]
        elif len(args)==1:
            self.x_comp = 0
            self.y_comp = 0
        self.vector = [self.x_comp,self.y_comp]
    
    def magnitude(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __abs__(self):
        return (self.x_comp**2+self.y_comp**2)**.5
    
    def __len__(self):
        return 2
    
    def add(self, other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __call__(self,ind):
        return self[ind[0]][ind[1]]
    
    def __add__(self, other):
        return Vector(vec_add(self.vector,other.vector))   #Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __str__(self):
        return  '({},{})'.format(self.x_comp,self.y_comp)
    
    def __mul__(a,b):
        if isinstance(a,Vector) and isinstance(b,(int,float)):
            return Vector(b*a.x_comp, b*a.y_comp)
#         elif isinstance(a,(int,float)) and isinstance(b,Vector):
#             return Vector(a*b.x_comp, a*b.y_comp)
        elif isinstance(a,Vector) and isinstance(b, Vector):
            # dot product
            return a.x_comp*b.x_comp+a.y_comp*b.y_comp
        else:
            return False
    
    def __rmul__(vector,scalar):
        return Vector(scalar*vector.x_comp, scalar*vector.y_comp)
    
    def __iadd__(self,other):
        return Vector(self.x_comp+other.x_comp, self.y_comp+other.y_comp)
    
    def __imul__(self,other):
        return self.__mul__(other)

In [93]:
def vec_add(a,b):
    return (a[0]+b[0],a[1]+b[1])

In [94]:
a = Vector([1,2])
b = Vector(3,4)
print(a+b)

(0,0)


In [67]:
a = Vector()
print(a)

0
(0,0)


In [68]:
b = Vector(2,4)
print(b)

2
(2,4)


In [69]:
d = Vector(2,4,5,6)
print(d)

4
(2,4)


In [72]:
e = Vector([1,2],[1,2,3,4])


2
([1, 2], [1, 2, 3, 4])


In [77]:
Vector([[1,2,3],[4,5,6]])

1
([[1, 2, 3], [4, 5, 6]],)
<class 'tuple'>
[[1, 2, 3], [4, 5, 6]]
